apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: erpstock
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_HTTP_PORTS: "8080"
  SeedDemoData__Enabled: "true"
