apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: erpstock

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - api.yaml
  - frontend.yaml
  - ingress.yaml

images:
  - name: gestionstock-api
    newName: gestionstock-api
    newTag: demo-data-v1
  - name: gestionstock-frontend
    newName: gestionstock-frontend
    newTag: k8s
