--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Articles" (
    "Id" integer NOT NULL,
    "Reference" text NOT NULL,
    "Designation" text NOT NULL,
    "ModeGestion" text NOT NULL,
    "CMUP" numeric NOT NULL,
    "DateCreation" timestamp with time zone NOT NULL,
    "FamilleArticleId" integer NOT NULL,
    "SuiviStock" integer DEFAULT 0 NOT NULL,
    "Type" integer DEFAULT 0 NOT NULL,
    "SeuilMinimum" integer DEFAULT 10 NOT NULL,
    "UniteMesure" character varying(30) DEFAULT 'Unité'::character varying NOT NULL
);


--
-- Name: Articles_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Articles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Articles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "DateDemande" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "Nom" character varying(100) DEFAULT ''::character varying NOT NULL,
    "Prenom" character varying(100) DEFAULT ''::character varying NOT NULL,
    "StatutApprobation" character varying(20) DEFAULT 'Acceptee'::character varying NOT NULL
);


--
-- Name: Depots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Depots" (
    "Id" integer NOT NULL,
    "Reference" text NOT NULL,
    "Nom" text NOT NULL,
    "DepotParentId" integer
);


--
-- Name: Depots_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Depots" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Depots_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Emplacements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Emplacements" (
    "Id" integer NOT NULL,
    "Zone" text NOT NULL,
    "Etagere" text NOT NULL,
    "Tiroir" text NOT NULL,
    "Code_Emplacement" text NOT NULL,
    "DepotId" integer NOT NULL
);


--
-- Name: Emplacements_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Emplacements" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Emplacements_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: FamillesArticles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."FamillesArticles" (
    "Id" integer NOT NULL,
    "Reference" text NOT NULL,
    "Nom" text NOT NULL,
    "FamilleParentId" integer
);


--
-- Name: FamillesArticles_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."FamillesArticles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FamillesArticles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MouvementsStock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."MouvementsStock" (
    "Id" integer NOT NULL,
    "Type" integer NOT NULL,
    "DateMouvement" timestamp with time zone NOT NULL,
    "Quantite" integer NOT NULL,
    "ArticleId" integer NOT NULL,
    "EmplacementSourceId" integer,
    "EmplacementDestinationId" integer,
    "PrixUnitaireEntree" numeric,
    "PrixUnitaireSortie" numeric
);


--
-- Name: MouvementsStock_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."MouvementsStock" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MouvementsStock_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Signalements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Signalements" (
    "Id" integer NOT NULL,
    "DateSignalement" timestamp with time zone NOT NULL,
    "QuantiteTheorique" integer NOT NULL,
    "QuantiteDetectee" integer NOT NULL,
    "Ecart" integer NOT NULL,
    "Statut" integer NOT NULL,
    "SignaleParUserId" character varying(450) NOT NULL,
    "SignalePar" character varying(256) NOT NULL,
    "ArticleId" integer NOT NULL,
    "EmplacementId" integer NOT NULL
);


--
-- Name: Signalements_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Signalements" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Signalements_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: StockLots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."StockLots" (
    "Id" integer NOT NULL,
    "QuantiteRestante" integer NOT NULL,
    "PrixUnitaire" numeric NOT NULL,
    "DateEntree" timestamp with time zone NOT NULL,
    "ArticleId" integer NOT NULL,
    "EmplacementId" integer NOT NULL
);


--
-- Name: StockLots_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."StockLots" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."StockLots_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Stocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Stocks" (
    "Id" integer NOT NULL,
    "Quantite" integer NOT NULL,
    "ArticleId" integer NOT NULL,
    "EmplacementId" integer NOT NULL
);


--
-- Name: Stocks_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Stocks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Stocks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: VerificationsStock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."VerificationsStock" (
    "Id" integer NOT NULL,
    "DateVerification" timestamp with time zone NOT NULL,
    "QuantiteTheorique" integer NOT NULL,
    "QuantiteDetectee" integer NOT NULL,
    "Ecart" integer NOT NULL,
    "PhotoUrl" text,
    "ArticleId" integer NOT NULL,
    "EmplacementId" integer NOT NULL
);


--
-- Name: VerificationsStock_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."VerificationsStock" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."VerificationsStock_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: Articles; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Articles" VALUES (16, 'hhhhh', 'lllll', 'FIFO', 0.02, '2026-08-27 18:08:34.575957+01', 3, 2, 1, 10, 'Unité');
INSERT INTO public."Articles" VALUES (1, 'ART001', 'Vis 7 mm inox', 'CMUP', 0.5148148148148148148148148148, '2026-08-07 10:06:18.095538+01', 1, 0, 0, 215, 'Unité');
INSERT INTO public."Articles" VALUES (2, 'ART002', 'Ecrou hexagonal M6 zingue', 'CMUP', 0.195, '2026-08-12 08:54:51.867575+01', 1, 0, 0, 110, 'Unité');
INSERT INTO public."Articles" VALUES (3, 'ART003', 'Rondelle plate M6 zinguee', 'CMUP', 0.05, '2026-08-12 08:54:51.929907+01', 1, 0, 0, 420, 'Unité');
INSERT INTO public."Articles" VALUES (4, 'ART004', 'Gants de protection nitrile', 'CMUP', 0.85, '2026-08-12 08:54:51.936648+01', 1, 0, 0, 43, 'Unité');
INSERT INTO public."Articles" VALUES (5, 'ART005', 'Ruban adhesif 48 mm', 'CMUP', 3.48, '2026-08-12 08:54:51.940984+01', 1, 0, 0, 29, 'Unité');
INSERT INTO public."Articles" VALUES (15, 'CCCF', 'FRRRR', 'CMUP', 200, '2026-08-27 12:01:16.370697+01', 1, 0, 0, 20, 'Unité');
INSERT INTO public."Articles" VALUES (8, 'DEMO-POM-003', 'Pompe de circulation', 'CMUP', 245, '2026-04-06 09:40:14.458232+01', 3, 0, 0, 3, 'Unité');
INSERT INTO public."Articles" VALUES (6, 'DEMO-VIS-001', 'Vis inox M6', 'CMUP', 0.85, '2026-03-07 09:40:14.458212+01', 3, 0, 0, 480, 'Unité');
INSERT INTO public."Articles" VALUES (9, 'DEMO-ROU-004', 'Roulement 6204', 'CMUP', 12.75, '2026-04-21 09:40:14.458232+01', 3, 0, 0, 32, 'Unité');
INSERT INTO public."Articles" VALUES (12, 'DEMO-FIL-007', 'Filtre hydraulique', 'CMUP', 31.50, '2026-06-15 09:40:14.458233+01', 3, 0, 0, 21, 'Unité');
INSERT INTO public."Articles" VALUES (7, 'DEMO-CAB-002', 'Câble industriel 5 m', 'CMUP', 18.40, '2026-03-22 09:40:14.458231+01', 4, 0, 0, 125, 'Unité');
INSERT INTO public."Articles" VALUES (11, 'DEMO-CAP-006', 'Capteur de proximité', 'CMUP', 76, '2026-05-31 09:40:14.458232+01', 4, 0, 0, 1, 'Unité');
INSERT INTO public."Articles" VALUES (13, 'DEMO-MOT-008', 'Moteur électrique', 'CMUP', 680, '2026-06-30 09:40:14.458233+01', 4, 0, 0, 2, 'Unité');
INSERT INTO public."Articles" VALUES (14, 'DEMO-ETI-009', 'Étiquette thermique', 'CMUP', 0.18, '2026-07-10 09:40:14.458233+01', 4, 0, 0, 160, 'Unité');
INSERT INTO public."Articles" VALUES (17, 'gggg', 'vis', 'CMUP', 0.23, '2026-08-28 08:42:26.503311+01', 5, 0, 1, 200, 'Unité');
INSERT INTO public."Articles" VALUES (10, 'DEMO-GAN-005', 'Gants de protection', 'CMUP', 6.20, '2026-05-11 09:40:14.458232+01', 6, 0, 0, 66, 'Unité');
INSERT INTO public."Articles" VALUES (21, 'dododo', 'bts', 'FIFO', 0.15, '2026-08-30 10:36:52.186177+01', 2, 0, 0, 5, 'g');


--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."AspNetRoles" VALUES ('d8b79bd7-f22f-4c95-8936-08a3bec9e632', 'SuperAdmin', 'SUPERADMIN', NULL);
INSERT INTO public."AspNetRoles" VALUES ('2d4e2f65-16c0-4353-b194-6e8d4dd6414d', 'Consultant', 'CONSULTANT', NULL);


--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."AspNetUserRoles" VALUES ('729b8e50-5aba-4976-a933-ec36de5345e7', 'd8b79bd7-f22f-4c95-8936-08a3bec9e632');
INSERT INTO public."AspNetUserRoles" VALUES ('5f9654a7-30f6-478e-81a1-ddcd300f471e', '2d4e2f65-16c0-4353-b194-6e8d4dd6414d');
INSERT INTO public."AspNetUserRoles" VALUES ('79bf2dfb-d4cf-458f-9ee4-6b628d73d1b7', '2d4e2f65-16c0-4353-b194-6e8d4dd6414d');
INSERT INTO public."AspNetUserRoles" VALUES ('42f410d6-21d9-4875-879b-9ce2a5fbd0e4', '2d4e2f65-16c0-4353-b194-6e8d4dd6414d');
INSERT INTO public."AspNetUserRoles" VALUES ('4efd54fd-51b7-4b6b-9797-a06c6cdbc8b4', '2d4e2f65-16c0-4353-b194-6e8d4dd6414d');


--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."AspNetUsers" VALUES ('5f9654a7-30f6-478e-81a1-ddcd300f471e', 'consultant@erpstock.local', 'CONSULTANT@ERPSTOCK.LOCAL', 'consultant@erpstock.local', 'CONSULTANT@ERPSTOCK.LOCAL', true, 'AQAAAAIAAYagAAAAEKFW6KJiuwFrs9D5Gpxj6YYWdIXofxAFhTOhYKoJg/2ePrB9Ft/llblYMv3E4ViTZg==', 'THIRJ3BYYYBEUSIV46LEPARGMBDE7JA6', 'c23e7f7d-cfd9-4f25-be6e-b0348441e94e', NULL, false, false, NULL, true, 0, '2026-08-30 09:11:26.222402+01', '', '', 'Acceptee');
INSERT INTO public."AspNetUsers" VALUES ('79bf2dfb-d4cf-458f-9ee4-6b628d73d1b7', 'employe@erpstock.local', 'EMPLOYE@ERPSTOCK.LOCAL', 'employe@erpstock.local', 'EMPLOYE@ERPSTOCK.LOCAL', true, 'AQAAAAIAAYagAAAAEBx/a7u6ksKOmNhLfzxz/3hDOmJzWkNlBhfARzbyfwdZG/16oQ3D7NgsZdTSoaN0HQ==', 'RPXXCJMXFLMWIFLBCJQC6VI7G5B2LSWY', 'ed1797a6-cd95-4be9-a438-d7b74a9b0f36', NULL, false, false, NULL, true, 0, '2026-08-30 09:11:26.222402+01', '', '', 'Acceptee');
INSERT INTO public."AspNetUsers" VALUES ('42f410d6-21d9-4875-879b-9ce2a5fbd0e4', 'ibtihel@erpstock.local', 'IBTIHEL@ERPSTOCK.LOCAL', 'ibtihel@erpstock.local', 'IBTIHEL@ERPSTOCK.LOCAL', true, 'AQAAAAIAAYagAAAAEBAta756Rx41pgAj1uQ7flFOETiosbBj90Qr2T3s3RRyxOKvrYGFCK3uw0XcXn0Jww==', 'U4GNOHJIKEAKXB2UBJVZ3YSYIQLOE4EP', 'fa903410-95a4-4323-a9fa-67240f78ba76', '+21625109836', false, false, NULL, true, 0, '2026-08-30 09:13:14.455425+01', 'MANAA', 'IBTIHEL', 'Acceptee');
INSERT INTO public."AspNetUsers" VALUES ('729b8e50-5aba-4976-a933-ec36de5345e7', 'admin@erpstock.local', 'ADMIN@ERPSTOCK.LOCAL', 'admin@erpstock.local', 'ADMIN@ERPSTOCK.LOCAL', true, 'AQAAAAIAAYagAAAAEIPnBmzyMFwB3ZO4XNE5hMCqcvoqH/43Vs9F8DFrTXdmewRgARa3TRoeSebQzaXyBg==', 'KFA2O3NW2LQ4ZKQZP4CSOAKZZ2HIJ5RZ', '016fe9f2-19bd-46d8-ba0e-06ee428fb0fc', '0556846500', false, false, NULL, true, 0, '2026-08-30 09:11:26.222402+01', 'manaa', 'Mohamed', 'Acceptee');
INSERT INTO public."AspNetUsers" VALUES ('4efd54fd-51b7-4b6b-9797-a06c6cdbc8b4', 'ali@erpstock.local', 'ALI@ERPSTOCK.LOCAL', 'ali@erpstock.local', 'ALI@ERPSTOCK.LOCAL', true, 'AQAAAAIAAYagAAAAEMvJHRN/LaTgFlVQjszf9FlYfwdGqxDrCKQ3cmmvLenAIGAhdNVP/Su9eAZwgZxv8w==', 'QJMJS2ZYAY66ZMYWBMMSTSCRYV2TNQIE', '5ebcd96b-950e-49d7-8dc1-28c2c9f88289', '+33556846500', false, false, NULL, true, 0, '2026-09-01 19:20:26.662486+01', 'Mathlouthi', 'ali', 'EnAttente');


--
-- Data for Name: Depots; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Depots" VALUES (1, 'DEP-001', 'Dépôt principal', NULL);
INSERT INTO public."Depots" VALUES (2, 'DEP-002', 'Dépôt atelier', 1);
INSERT INTO public."Depots" VALUES (3, 'DEP-003', 'Dépôt réserve', 1);
INSERT INTO public."Depots" VALUES (4, 'DEP-004', 'Dépôt expédition', 1);
INSERT INTO public."Depots" VALUES (5, 'DEPO-222', 'principal 2', NULL);


--
-- Data for Name: Emplacements; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Emplacements" VALUES (1, 'A', '01', '01', 'A-01-01', 1);
INSERT INTO public."Emplacements" VALUES (2, 'A', '01', '02', 'A-01-02', 1);
INSERT INTO public."Emplacements" VALUES (3, 'A', '02', '01', 'A-02-01', 1);
INSERT INTO public."Emplacements" VALUES (4, 'B', '01', '01', 'B-01-01', 1);
INSERT INTO public."Emplacements" VALUES (5, 'B', '01', '02', 'B-01-02', 1);
INSERT INTO public."Emplacements" VALUES (6, 'Atelier', 'A1', '01', 'ATELIER-A1-01', 2);
INSERT INTO public."Emplacements" VALUES (7, 'Atelier', 'A1', '02', 'ATELIER-A1-02', 2);
INSERT INTO public."Emplacements" VALUES (8, 'Réserve', 'B2', '01', 'RESERVE-B2-01', 3);
INSERT INTO public."Emplacements" VALUES (9, 'Réserve', 'B2', '02', 'RESERVE-B2-02', 3);
INSERT INTO public."Emplacements" VALUES (10, 'Expédition', 'E1', '01', 'EXPEDITION-E1-01', 4);


--
-- Data for Name: FamillesArticles; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."FamillesArticles" VALUES (1, 'FAM-001', 'Famille non classée', NULL);
INSERT INTO public."FamillesArticles" VALUES (2, 'FAM-002', 'Fournitures industrielles', NULL);
INSERT INTO public."FamillesArticles" VALUES (3, 'FAM-003', 'Composants mécaniques', 2);
INSERT INTO public."FamillesArticles" VALUES (4, 'FAM-004', 'Composants électriques', 2);
INSERT INTO public."FamillesArticles" VALUES (5, 'FAM-005', 'Consommables et sécurité', NULL);
INSERT INTO public."FamillesArticles" VALUES (6, 'FAM-006', 'Équipements de protection', 5);


--
-- Data for Name: MouvementsStock; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."MouvementsStock" VALUES (2, 1, '2026-08-12 08:54:52.027964+01', 100, 1, NULL, 1, 0.52, NULL);
INSERT INTO public."MouvementsStock" VALUES (3, 3, '2026-08-12 08:54:52.099893+01', 30, 1, 1, 2, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (4, 2, '2026-08-12 08:54:52.12396+01', 20, 1, 1, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (5, 1, '2026-08-12 08:54:52.143685+01', 250, 2, NULL, 3, 0.18, NULL);
INSERT INTO public."MouvementsStock" VALUES (6, 1, '2026-08-12 08:54:52.154344+01', 150, 2, NULL, 3, 0.22, NULL);
INSERT INTO public."MouvementsStock" VALUES (7, 2, '2026-08-12 08:54:52.16564+01', 70, 2, 3, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (8, 1, '2026-08-12 08:54:52.17441+01', 500, 3, NULL, 4, 0.05, NULL);
INSERT INTO public."MouvementsStock" VALUES (9, 3, '2026-08-12 08:54:52.182519+01', 150, 3, 4, 5, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (10, 2, '2026-08-12 08:54:52.191786+01', 80, 3, 4, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (11, 1, '2026-08-12 08:54:52.201489+01', 100, 4, NULL, 4, 0.85, NULL);
INSERT INTO public."MouvementsStock" VALUES (12, 2, '2026-08-12 08:54:52.209641+01', 15, 4, 4, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (13, 1, '2026-08-12 08:54:52.21834+01', 60, 5, NULL, 5, 3.4, NULL);
INSERT INTO public."MouvementsStock" VALUES (14, 1, '2026-08-12 08:54:52.226782+01', 40, 5, NULL, 5, 3.6, NULL);
INSERT INTO public."MouvementsStock" VALUES (15, 2, '2026-08-12 08:54:52.237711+01', 12, 5, 5, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (1, 1, '2026-08-10 11:39:21.277788+01', 35, 1, NULL, 1, 0.50, NULL);
INSERT INTO public."MouvementsStock" VALUES (16, 1, '2026-06-18 18:40:14.639122+01', 240, 6, NULL, 6, 0.78, NULL);
INSERT INTO public."MouvementsStock" VALUES (17, 1, '2026-06-22 18:40:14.639282+01', 120, 7, NULL, 8, 17.50, NULL);
INSERT INTO public."MouvementsStock" VALUES (18, 1, '2026-06-26 18:40:14.639283+01', 8, 8, NULL, 6, 238, NULL);
INSERT INTO public."MouvementsStock" VALUES (19, 1, '2026-07-01 18:40:14.639283+01', 45, 9, NULL, 9, 12.20, NULL);
INSERT INTO public."MouvementsStock" VALUES (20, 1, '2026-07-05 18:40:14.639284+01', 90, 10, NULL, 10, 5.90, NULL);
INSERT INTO public."MouvementsStock" VALUES (21, 1, '2026-07-08 18:40:14.639284+01', 30, 12, NULL, 8, 30, NULL);
INSERT INTO public."MouvementsStock" VALUES (22, 1, '2026-07-11 18:40:14.639285+01', 600, 14, NULL, 10, 0.16, NULL);
INSERT INTO public."MouvementsStock" VALUES (23, 2, '2026-07-16 18:40:14.639285+01', 35, 6, 6, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (24, 2, '2026-07-18 18:40:14.639293+01', 20, 7, 8, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (25, 2, '2026-07-20 18:40:14.639293+01', 16, 10, 10, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (26, 2, '2026-07-22 18:40:14.639294+01', 80, 14, 10, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (27, 1, '2026-07-24 18:40:14.639294+01', 6, 11, NULL, 7, 74, NULL);
INSERT INTO public."MouvementsStock" VALUES (28, 1, '2026-07-26 18:40:14.639295+01', 3, 13, NULL, 9, 665, NULL);
INSERT INTO public."MouvementsStock" VALUES (29, 3, '2026-07-28 18:40:14.639295+01', 80, 6, 6, 8, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (30, 1, '2026-07-30 18:40:14.639296+01', 150, 7, NULL, 10, 19.10, NULL);
INSERT INTO public."MouvementsStock" VALUES (31, 2, '2026-08-02 18:40:14.639296+01', 13, 9, 9, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (32, 2, '2026-08-04 18:40:14.639296+01', 9, 12, 8, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (33, 2, '2026-08-06 18:40:14.639297+01', 25, 6, 8, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (34, 1, '2026-08-08 18:40:14.639297+01', 25, 10, NULL, 10, 6.40, NULL);
INSERT INTO public."MouvementsStock" VALUES (35, 2, '2026-08-10 18:40:14.639298+01', 40, 14, 10, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (36, 2, '2026-08-12 18:40:14.639298+01', 30, 7, 10, NULL, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (37, 1, '2026-08-13 18:40:14.639299+01', 120, 6, NULL, 6, 0.88, NULL);
INSERT INTO public."MouvementsStock" VALUES (38, 1, '2026-08-20 20:43:52.349604+01', 1015, 1, NULL, 1, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (39, 1, '2026-08-20 20:53:07.816504+01', 2, 11, NULL, 7, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (40, 1, '2026-08-27 11:40:46.427016+01', 58, 10, NULL, 10, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (41, 1, '2026-08-27 12:04:37.344163+01', 20, 15, NULL, 1, 200, NULL);
INSERT INTO public."MouvementsStock" VALUES (42, 1, '2026-08-28 08:42:26.581988+01', 400, 17, NULL, 4, 23, NULL);
INSERT INTO public."MouvementsStock" VALUES (43, 3, '2026-08-28 09:04:39.723204+01', 200, 17, 4, 5, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (44, 1, '2026-08-28 09:06:19.707197+01', 200, 17, NULL, 4, NULL, NULL);
INSERT INTO public."MouvementsStock" VALUES (48, 2, '2026-08-28 11:52:01.048744+01', 700, 1, 1, NULL, NULL, 0.5148148148148148148148148148);
INSERT INTO public."MouvementsStock" VALUES (49, 1, '2026-08-28 11:53:11.413843+01', 2, 13, NULL, 9, 680, NULL);
INSERT INTO public."MouvementsStock" VALUES (50, 1, '2026-08-30 10:36:52.242824+01', 5, 21, NULL, 5, 0.15, NULL);


--
-- Data for Name: Signalements; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Signalements" VALUES (26, '2026-08-28 09:05:06.420333+01', 200, 400, 200, 2, '729b8e50-5aba-4976-a933-ec36de5345e7', 'admin@erpstock.local', 17, 4);
INSERT INTO public."Signalements" VALUES (27, '2026-08-28 11:24:27.21214+01', 1100, 400, -700, 2, '729b8e50-5aba-4976-a933-ec36de5345e7', 'admin@erpstock.local', 1, 1);
INSERT INTO public."Signalements" VALUES (28, '2026-08-28 11:52:57.200069+01', 2, 4, 2, 2, '729b8e50-5aba-4976-a933-ec36de5345e7', 'admin@erpstock.local', 13, 9);


--
-- Data for Name: StockLots; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."StockLots" VALUES (1, 30, 0.5148148148148148148148148148, '2026-08-07 10:06:18.095538+01', 1, 2);
INSERT INTO public."StockLots" VALUES (2, 330, 0.195, '2026-08-12 08:54:51.867575+01', 2, 3);
INSERT INTO public."StockLots" VALUES (3, 150, 0.05, '2026-08-12 08:54:51.929907+01', 3, 5);
INSERT INTO public."StockLots" VALUES (4, 270, 0.05, '2026-08-12 08:54:51.929907+01', 3, 4);
INSERT INTO public."StockLots" VALUES (5, 85, 0.85, '2026-08-12 08:54:51.936648+01', 4, 4);
INSERT INTO public."StockLots" VALUES (6, 88, 3.48, '2026-08-12 08:54:51.940984+01', 5, 5);
INSERT INTO public."StockLots" VALUES (7, 350, 0.85, '2026-03-07 09:40:14.458212+01', 6, 6);
INSERT INTO public."StockLots" VALUES (8, 130, 0.85, '2026-03-07 09:40:14.458212+01', 6, 8);
INSERT INTO public."StockLots" VALUES (9, 170, 18.40, '2026-03-22 09:40:14.458231+01', 7, 8);
INSERT INTO public."StockLots" VALUES (10, 80, 18.40, '2026-03-22 09:40:14.458231+01', 7, 10);
INSERT INTO public."StockLots" VALUES (11, 9, 245, '2026-04-06 09:40:14.458232+01', 8, 6);
INSERT INTO public."StockLots" VALUES (12, 32, 12.75, '2026-04-21 09:40:14.458232+01', 9, 9);
INSERT INTO public."StockLots" VALUES (13, 21, 31.50, '2026-06-15 09:40:14.458233+01', 12, 8);
INSERT INTO public."StockLots" VALUES (15, 480, 0.18, '2026-07-10 09:40:14.458233+01', 14, 10);
INSERT INTO public."StockLots" VALUES (17, 5, 76, '2026-05-31 09:40:14.458232+01', 11, 7);
INSERT INTO public."StockLots" VALUES (18, 132, 6.20, '2026-05-11 09:40:14.458232+01', 10, 10);
INSERT INTO public."StockLots" VALUES (19, 20, 200, '2026-08-27 12:01:16.370697+01', 15, 1);
INSERT INTO public."StockLots" VALUES (20, 200, 23, '2026-08-28 08:42:26.503311+01', 17, 5);
INSERT INTO public."StockLots" VALUES (21, 400, 23, '2026-08-28 08:42:26.503311+01', 17, 4);
INSERT INTO public."StockLots" VALUES (16, 400, 0.5148148148148148148148148148, '2026-08-07 10:06:18.095538+01', 1, 1);
INSERT INTO public."StockLots" VALUES (14, 0, 680, '2026-06-30 09:40:14.458233+01', 13, 9);
INSERT INTO public."StockLots" VALUES (23, 0, 680, '2026-08-28 11:53:11.413843+01', 13, 9);
INSERT INTO public."StockLots" VALUES (24, 4, 680, '2026-08-30 10:35:49.866026+01', 13, 9);
INSERT INTO public."StockLots" VALUES (25, 5, 0.15, '2026-08-30 10:36:52.239491+01', 21, 5);


--
-- Data for Name: Stocks; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Stocks" VALUES (3, 30, 1, 2);
INSERT INTO public."Stocks" VALUES (4, 330, 2, 3);
INSERT INTO public."Stocks" VALUES (6, 150, 3, 5);
INSERT INTO public."Stocks" VALUES (5, 270, 3, 4);
INSERT INTO public."Stocks" VALUES (7, 85, 4, 4);
INSERT INTO public."Stocks" VALUES (8, 88, 5, 5);
INSERT INTO public."Stocks" VALUES (9, 350, 6, 6);
INSERT INTO public."Stocks" VALUES (10, 130, 6, 8);
INSERT INTO public."Stocks" VALUES (11, 170, 7, 8);
INSERT INTO public."Stocks" VALUES (12, 80, 7, 10);
INSERT INTO public."Stocks" VALUES (13, 9, 8, 6);
INSERT INTO public."Stocks" VALUES (14, 32, 9, 9);
INSERT INTO public."Stocks" VALUES (17, 21, 12, 8);
INSERT INTO public."Stocks" VALUES (19, 480, 14, 10);
INSERT INTO public."Stocks" VALUES (16, 5, 11, 7);
INSERT INTO public."Stocks" VALUES (15, 132, 10, 10);
INSERT INTO public."Stocks" VALUES (20, 20, 15, 1);
INSERT INTO public."Stocks" VALUES (22, 200, 17, 5);
INSERT INTO public."Stocks" VALUES (21, 400, 17, 4);
INSERT INTO public."Stocks" VALUES (1, 400, 1, 1);
INSERT INTO public."Stocks" VALUES (18, 4, 13, 9);
INSERT INTO public."Stocks" VALUES (26, 5, 21, 5);


--
-- Data for Name: VerificationsStock; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."VerificationsStock" VALUES (33, '2026-08-28 09:03:44.802666+01', 400, 400, 0, NULL, 17, 4);
INSERT INTO public."VerificationsStock" VALUES (34, '2026-08-28 09:05:06.420333+01', 200, 400, 200, NULL, 17, 4);
INSERT INTO public."VerificationsStock" VALUES (35, '2026-08-28 09:17:41.967886+01', 400, 400, 0, NULL, 17, 4);
INSERT INTO public."VerificationsStock" VALUES (36, '2026-08-28 11:24:27.21214+01', 1100, 400, -700, NULL, 1, 1);
INSERT INTO public."VerificationsStock" VALUES (37, '2026-08-28 11:52:57.200069+01', 2, 4, 2, NULL, 13, 9);


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20260806103930_InitialCreate', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260810103148_AddMouvementsStock', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260812072835_AddPrixUnitaireEntreeToMouvementStock', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260812082255_AddVerificationStock', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260812103740_AddIdentityAndSignalements', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260818082928_AddUnitesParCarton', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260827141810_AddDepotsEtFamilles', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260827143243_CleanHistoriesAndSeedOrganisation', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260827160000_NormalizeOrganisationReferences', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260827170000_RemoveOrganisationReferenceConstraints', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260828092849_AddStockLotsAndOutputCost', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260830120000_AddConsultantAccountApproval', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260830143000_AddArticleMinimumStockThreshold', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260830150000_InitializeArticleMinimumStockThreshold', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260830160000_RemoveArticleCartonManagement', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260830170000_SetExistingArticleStockThresholds', '9.0.18');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260830180000_NormalizeExistingArticleUnits', '9.0.18');


--
-- Name: Articles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Articles_Id_seq"', 21, true);


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: Depots_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Depots_Id_seq"', 5, true);


--
-- Name: Emplacements_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Emplacements_Id_seq"', 10, true);


--
-- Name: FamillesArticles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."FamillesArticles_Id_seq"', 8, true);


--
-- Name: MouvementsStock_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."MouvementsStock_Id_seq"', 50, true);


--
-- Name: Signalements_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Signalements_Id_seq"', 28, true);


--
-- Name: StockLots_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."StockLots_Id_seq"', 25, true);


--
-- Name: Stocks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Stocks_Id_seq"', 26, true);


--
-- Name: VerificationsStock_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."VerificationsStock_Id_seq"', 37, true);


--
-- Name: Articles PK_Articles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Articles"
    ADD CONSTRAINT "PK_Articles" PRIMARY KEY ("Id");


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: Depots PK_Depots; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Depots"
    ADD CONSTRAINT "PK_Depots" PRIMARY KEY ("Id");


--
-- Name: Emplacements PK_Emplacements; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Emplacements"
    ADD CONSTRAINT "PK_Emplacements" PRIMARY KEY ("Id");


--
-- Name: FamillesArticles PK_FamillesArticles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FamillesArticles"
    ADD CONSTRAINT "PK_FamillesArticles" PRIMARY KEY ("Id");


--
-- Name: MouvementsStock PK_MouvementsStock; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MouvementsStock"
    ADD CONSTRAINT "PK_MouvementsStock" PRIMARY KEY ("Id");


--
-- Name: Signalements PK_Signalements; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Signalements"
    ADD CONSTRAINT "PK_Signalements" PRIMARY KEY ("Id");


--
-- Name: StockLots PK_StockLots; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."StockLots"
    ADD CONSTRAINT "PK_StockLots" PRIMARY KEY ("Id");


--
-- Name: Stocks PK_Stocks; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Stocks"
    ADD CONSTRAINT "PK_Stocks" PRIMARY KEY ("Id");


--
-- Name: VerificationsStock PK_VerificationsStock; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."VerificationsStock"
    ADD CONSTRAINT "PK_VerificationsStock" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_Articles_FamilleArticleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Articles_FamilleArticleId" ON public."Articles" USING btree ("FamilleArticleId");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_Depots_DepotParentId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Depots_DepotParentId" ON public."Depots" USING btree ("DepotParentId");


--
-- Name: IX_Emplacements_DepotId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Emplacements_DepotId" ON public."Emplacements" USING btree ("DepotId");


--
-- Name: IX_FamillesArticles_FamilleParentId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_FamillesArticles_FamilleParentId" ON public."FamillesArticles" USING btree ("FamilleParentId");


--
-- Name: IX_MouvementsStock_ArticleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_MouvementsStock_ArticleId" ON public."MouvementsStock" USING btree ("ArticleId");


--
-- Name: IX_MouvementsStock_EmplacementDestinationId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_MouvementsStock_EmplacementDestinationId" ON public."MouvementsStock" USING btree ("EmplacementDestinationId");


--
-- Name: IX_MouvementsStock_EmplacementSourceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_MouvementsStock_EmplacementSourceId" ON public."MouvementsStock" USING btree ("EmplacementSourceId");


--
-- Name: IX_Signalements_ArticleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Signalements_ArticleId" ON public."Signalements" USING btree ("ArticleId");


--
-- Name: IX_Signalements_EmplacementId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Signalements_EmplacementId" ON public."Signalements" USING btree ("EmplacementId");


--
-- Name: IX_StockLots_ArticleId_EmplacementId_DateEntree; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_StockLots_ArticleId_EmplacementId_DateEntree" ON public."StockLots" USING btree ("ArticleId", "EmplacementId", "DateEntree");


--
-- Name: IX_StockLots_EmplacementId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_StockLots_EmplacementId" ON public."StockLots" USING btree ("EmplacementId");


--
-- Name: IX_Stocks_ArticleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Stocks_ArticleId" ON public."Stocks" USING btree ("ArticleId");


--
-- Name: IX_Stocks_EmplacementId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Stocks_EmplacementId" ON public."Stocks" USING btree ("EmplacementId");


--
-- Name: IX_VerificationsStock_ArticleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_VerificationsStock_ArticleId" ON public."VerificationsStock" USING btree ("ArticleId");


--
-- Name: IX_VerificationsStock_EmplacementId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_VerificationsStock_EmplacementId" ON public."VerificationsStock" USING btree ("EmplacementId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: Articles FK_Articles_FamillesArticles_FamilleArticleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Articles"
    ADD CONSTRAINT "FK_Articles_FamillesArticles_FamilleArticleId" FOREIGN KEY ("FamilleArticleId") REFERENCES public."FamillesArticles"("Id") ON DELETE RESTRICT;


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Depots FK_Depots_Depots_DepotParentId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Depots"
    ADD CONSTRAINT "FK_Depots_Depots_DepotParentId" FOREIGN KEY ("DepotParentId") REFERENCES public."Depots"("Id") ON DELETE RESTRICT;


--
-- Name: Emplacements FK_Emplacements_Depots_DepotId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Emplacements"
    ADD CONSTRAINT "FK_Emplacements_Depots_DepotId" FOREIGN KEY ("DepotId") REFERENCES public."Depots"("Id") ON DELETE RESTRICT;


--
-- Name: FamillesArticles FK_FamillesArticles_FamillesArticles_FamilleParentId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FamillesArticles"
    ADD CONSTRAINT "FK_FamillesArticles_FamillesArticles_FamilleParentId" FOREIGN KEY ("FamilleParentId") REFERENCES public."FamillesArticles"("Id") ON DELETE RESTRICT;


--
-- Name: MouvementsStock FK_MouvementsStock_Articles_ArticleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MouvementsStock"
    ADD CONSTRAINT "FK_MouvementsStock_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES public."Articles"("Id") ON DELETE RESTRICT;


--
-- Name: MouvementsStock FK_MouvementsStock_Emplacements_EmplacementDestinationId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MouvementsStock"
    ADD CONSTRAINT "FK_MouvementsStock_Emplacements_EmplacementDestinationId" FOREIGN KEY ("EmplacementDestinationId") REFERENCES public."Emplacements"("Id") ON DELETE RESTRICT;


--
-- Name: MouvementsStock FK_MouvementsStock_Emplacements_EmplacementSourceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MouvementsStock"
    ADD CONSTRAINT "FK_MouvementsStock_Emplacements_EmplacementSourceId" FOREIGN KEY ("EmplacementSourceId") REFERENCES public."Emplacements"("Id") ON DELETE RESTRICT;


--
-- Name: Signalements FK_Signalements_Articles_ArticleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Signalements"
    ADD CONSTRAINT "FK_Signalements_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES public."Articles"("Id") ON DELETE RESTRICT;


--
-- Name: Signalements FK_Signalements_Emplacements_EmplacementId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Signalements"
    ADD CONSTRAINT "FK_Signalements_Emplacements_EmplacementId" FOREIGN KEY ("EmplacementId") REFERENCES public."Emplacements"("Id") ON DELETE RESTRICT;


--
-- Name: StockLots FK_StockLots_Articles_ArticleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."StockLots"
    ADD CONSTRAINT "FK_StockLots_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES public."Articles"("Id") ON DELETE RESTRICT;


--
-- Name: StockLots FK_StockLots_Emplacements_EmplacementId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."StockLots"
    ADD CONSTRAINT "FK_StockLots_Emplacements_EmplacementId" FOREIGN KEY ("EmplacementId") REFERENCES public."Emplacements"("Id") ON DELETE RESTRICT;


--
-- Name: Stocks FK_Stocks_Articles_ArticleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Stocks"
    ADD CONSTRAINT "FK_Stocks_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES public."Articles"("Id") ON DELETE CASCADE;


--
-- Name: Stocks FK_Stocks_Emplacements_EmplacementId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Stocks"
    ADD CONSTRAINT "FK_Stocks_Emplacements_EmplacementId" FOREIGN KEY ("EmplacementId") REFERENCES public."Emplacements"("Id") ON DELETE CASCADE;


--
-- Name: VerificationsStock FK_VerificationsStock_Articles_ArticleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."VerificationsStock"
    ADD CONSTRAINT "FK_VerificationsStock_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES public."Articles"("Id") ON DELETE RESTRICT;


--
-- Name: VerificationsStock FK_VerificationsStock_Emplacements_EmplacementId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."VerificationsStock"
    ADD CONSTRAINT "FK_VerificationsStock_Emplacements_EmplacementId" FOREIGN KEY ("EmplacementId") REFERENCES public."Emplacements"("Id") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

