// <auto-generated />
using System;
using ERPStock.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERPStock.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812072835_AddPrixUnitaireEntreeToMouvementStock")]
    partial class AddPrixUnitaireEntreeToMouvementStock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ERPStock.Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CMUP")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModeGestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Emplacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code_Emplacement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Etagere")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tiroir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Emplacements");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmplacementDestinationId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmplacementSourceId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrixUnitaireEntree")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("EmplacementDestinationId");

                    b.HasIndex("EmplacementSourceId");

                    b.ToTable("MouvementsStock");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("EmplacementId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("EmplacementId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.MouvementStock", b =>
                {
                    b.HasOne("ERPStock.Domain.Entities.Article", "Article")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPStock.Domain.Entities.Emplacement", "EmplacementDestination")
                        .WithMany("MouvementsDestination")
                        .HasForeignKey("EmplacementDestinationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPStock.Domain.Entities.Emplacement", "EmplacementSource")
                        .WithMany("MouvementsSource")
                        .HasForeignKey("EmplacementSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Article");

                    b.Navigation("EmplacementDestination");

                    b.Navigation("EmplacementSource");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Stock", b =>
                {
                    b.HasOne("ERPStock.Domain.Entities.Article", "Article")
                        .WithMany("Stocks")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPStock.Domain.Entities.Emplacement", "Emplacement")
                        .WithMany("Stocks")
                        .HasForeignKey("EmplacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Emplacement");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Article", b =>
                {
                    b.Navigation("MouvementsStock");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Emplacement", b =>
                {
                    b.Navigation("MouvementsDestination");

                    b.Navigation("MouvementsSource");

                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
