// <auto-generated />
using System;
using ERPStock.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERPStock.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ERPStock.Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CMUP")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FamilleArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("ModeGestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuiviStock")
                        .HasColumnType("integer");

                    b.Property<int>("SeuilMinimum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UniteMesure")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Unité");

                    b.HasKey("Id");

                    b.HasIndex("FamilleArticleId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Depot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepotParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepotParentId");

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Emplacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code_Emplacement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DepotId")
                        .HasColumnType("integer");

                    b.Property<string>("Etagere")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tiroir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.ToTable("Emplacements");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.FamilleArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FamilleParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamilleParentId");

                    b.ToTable("FamillesArticles");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmplacementDestinationId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmplacementSourceId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrixUnitaireEntree")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrixUnitaireSortie")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("EmplacementDestinationId");

                    b.HasIndex("EmplacementSourceId");

                    b.ToTable("MouvementsStock");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Signalement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateSignalement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ecart")
                        .HasColumnType("integer");

                    b.Property<int>("EmplacementId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteDetectee")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteTheorique")
                        .HasColumnType("integer");

                    b.Property<string>("SignalePar")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SignaleParUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("EmplacementId");

                    b.ToTable("Signalements");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("EmplacementId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("EmplacementId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.StockLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateEntree")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmplacementId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("numeric");

                    b.Property<int>("QuantiteRestante")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmplacementId");

                    b.HasIndex("ArticleId", "EmplacementId", "DateEntree");

                    b.ToTable("StockLots");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.VerificationStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateVerification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ecart")
                        .HasColumnType("integer");

                    b.Property<int>("EmplacementId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("QuantiteDetectee")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteTheorique")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("EmplacementId");

                    b.ToTable("VerificationsStock");
                });

            modelBuilder.Entity("ERPStock.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateDemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("StatutApprobation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Acceptee");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Article", b =>
                {
                    b.HasOne("ERPStock.Domain.Entities.FamilleArticle", "FamilleArticle")
                        .WithMany("Articles")
                        .HasForeignKey("FamilleArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FamilleArticle");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Depot", b =>
                {
                    b.HasOne("ERPStock.Domain.Entities.Depot", "DepotParent")
                        .WithMany("DepotsEnfants")
                        .HasForeignKey("DepotParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DepotParent");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Emplacement", b =>
                {
                    b.HasOne("ERPStock.Domain.Entities.Depot", "Depot")
                        .WithMany("Emplacements")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.FamilleArticle", b =>
                {
                    b.HasOne("ERPStock.Domain.Entities.FamilleArticle", "FamilleParent")
                        .WithMany("FamillesEnfants")
                        .HasForeignKey("FamilleParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FamilleParent");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.MouvementStock", b =>
                {
                    b.HasOne("ERPStock.Domain.Entities.Article", "Article")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPStock.Domain.Entities.Emplacement", "EmplacementDestination")
                        .WithMany("MouvementsDestination")
                        .HasForeignKey("EmplacementDestinationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPStock.Domain.Entities.Emplacement", "EmplacementSource")
                        .WithMany("MouvementsSource")
                        .HasForeignKey("EmplacementSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Article");

                    b.Navigation("EmplacementDestination");

                    b.Navigation("EmplacementSource");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Signalement", b =>
                {
                    b.HasOne("ERPStock.Domain.Entities.Article", "Article")
                        .WithMany("Signalements")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPStock.Domain.Entities.Emplacement", "Emplacement")
                        .WithMany("Signalements")
                        .HasForeignKey("EmplacementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Emplacement");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Stock", b =>
                {
                    b.HasOne("ERPStock.Domain.Entities.Article", "Article")
                        .WithMany("Stocks")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPStock.Domain.Entities.Emplacement", "Emplacement")
                        .WithMany("Stocks")
                        .HasForeignKey("EmplacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Emplacement");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.StockLot", b =>
                {
                    b.HasOne("ERPStock.Domain.Entities.Article", "Article")
                        .WithMany("LotsStock")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPStock.Domain.Entities.Emplacement", "Emplacement")
                        .WithMany("LotsStock")
                        .HasForeignKey("EmplacementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Emplacement");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.VerificationStock", b =>
                {
                    b.HasOne("ERPStock.Domain.Entities.Article", "Article")
                        .WithMany("VerificationsStock")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPStock.Domain.Entities.Emplacement", "Emplacement")
                        .WithMany("VerificationsStock")
                        .HasForeignKey("EmplacementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Emplacement");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ERPStock.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ERPStock.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPStock.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ERPStock.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Article", b =>
                {
                    b.Navigation("LotsStock");

                    b.Navigation("MouvementsStock");

                    b.Navigation("Signalements");

                    b.Navigation("Stocks");

                    b.Navigation("VerificationsStock");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Depot", b =>
                {
                    b.Navigation("DepotsEnfants");

                    b.Navigation("Emplacements");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.Emplacement", b =>
                {
                    b.Navigation("LotsStock");

                    b.Navigation("MouvementsDestination");

                    b.Navigation("MouvementsSource");

                    b.Navigation("Signalements");

                    b.Navigation("Stocks");

                    b.Navigation("VerificationsStock");
                });

            modelBuilder.Entity("ERPStock.Domain.Entities.FamilleArticle", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("FamillesEnfants");
                });
#pragma warning restore 612, 618
        }
    }
}
